### ISSUE TITLE
Build failed, unresolve dependency 'com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar'

### ISSUE THREAD

**Issue by jerome-cirrios** [spring-cloud-samples/brewery#7]
My system is an Ubuntu 14.04 LTS with java 1.8.0_66.

The result of ./gradlew clean build

```           
:acceptance-tests:clean UP-TO-DATE
:brewing:clean UP-TO-DATE
:common:clean UP-TO-DATE
:config-server:clean UP-TO-DATE
:eureka:clean UP-TO-DATE
:presenting:clean UP-TO-DATE
:zipkin-server:clean UP-TO-DATE
:zookeeper:clean UP-TO-DATE
:zuul:clean UP-TO-DATE
:common:compileJava
Download http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-sleuth-core/1.0.0.BUILD-SNAPSHOT/spring-cloud-sleuth-core-1.0.0.BUILD-20160112.084458-234.pom

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':common:compile'.
> Could not find org.springframework.cloud:spring-cloud-sleuth-stream:.
  Required by:
      io.spring.cloud.samples.brewery:common:CD-000
> Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT.
  Required by:
      io.spring.cloud.samples.brewery:common:CD-000 > org.springframework.cloud:spring-cloud-starter-sleuth:1.0.0.BUILD-SNAPSHOT
   > Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT.
      > Could not parse POM http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-sleuth-core/1.0.0.BUILD-SNAPSHOT/spring-cloud-sleuth-core-1.0.0.BUILD-20160112.084458-234.pom
         > Unable to resolve version for dependency 'org.assertj:assertj-core:jar'
> Could not resolve org.springframework.cloud:spring-cloud-netflix-core:1.1.0.BUILD-SNAPSHOT.
  Required by:
      io.spring.cloud.samples.brewery:common:CD-000 > org.springframework.cloud:spring-cloud-starter-hystrix:1.1.0.BUILD-SNAPSHOT
   > Could not resolve org.springframework.cloud:spring-cloud-netflix-core:1.1.0.BUILD-SNAPSHOT.
      > Could not parse POM http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-netflix-core/1.1.0.BUILD-SNAPSHOT/spring-cloud-netflix-core-1.1.0.BUILD-20160112.000848-235.pom
         > Unable to resolve version for dependency 'com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I have clean my gradle cache, no effect. Any ideas ?

**Comment by marcingrzejszczak** [comment]
yup, we've been changing the build structure in Sleuth. We must have done sth wrong ;) Thx for pointing this out!

**Comment by marcingrzejszczak** [comment]
Is this issue still there? I've managed to build it successfully?

**Comment by jerome-cirrios** [comment]
I have another issue now ! 

*version for dependency 'org.assertj:assertj-core:jar'*

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':common:compile'.
> Could not resolve org.springframework.cloud:spring-cloud-starter-hystrix:1.1.0.BUILD-SNAPSHOT.
  Required by:
      io.spring.cloud.samples.brewery:common:CD-000
   > Could not resolve org.springframework.cloud:spring-cloud-starter-hystrix:1.1.0.BUILD-SNAPSHOT.
      > Could not parse POM http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-starter-hystrix/1.1.0.BUILD-SNAPSHOT/spring-cloud-starter-hystrix-1.1.0.BUILD-20160112.230312-221.pom
         > Unable to resolve version for dependency 'org.springframework.cloud:spring-cloud-starter-archaius:jar'
> Could not find org.springframework.cloud:spring-cloud-sleuth-stream:.
  Required by:
      io.spring.cloud.samples.brewery:common:CD-000
> Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT.
  Required by:
      io.spring.cloud.samples.brewery:common:CD-000 > org.springframework.cloud:spring-cloud-starter-sleuth:1.0.0.BUILD-SNAPSHOT
   > Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT.
      > Could not parse POM http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-sleuth-core/1.0.0.BUILD-SNAPSHOT/spring-cloud-sleuth-core-1.0.0.BUILD-20160113.111416-247.pom
         > Unable to resolve version for dependency 'org.assertj:assertj-core:jar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by marcingrzejszczak** [comment]
Can you run the build in `debug` mode? 

```
./gradlew clean build --debug
```

Then can you go to Gitter - https://gitter.im/marcingrzejszczak and send me a file with that log?

**Comment by marcingrzejszczak** [comment]
We've fixed the issue by doing some local installations of projects. Most likely we have published a couple of broken poms to artifactory.

**Comment by rm2013** [comment]
I am still seeing this issue, please point me to the work arounds. Thx

**Comment by marcingrzejszczak** [comment]
Hi! I confirm that I see it too. We're working on fixing those

**Comment by marcingrzejszczak** [comment]
the issues are fixed - please try again now

**Comment by rm2013** [comment]
Still the same 
 Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT

**Comment by marcingrzejszczak** [comment]
can you paste the whole log please?

**Comment by rm2013** [comment]
14:39:02.224 [ERROR] [org.gradle.BuildExceptionReporter] 
14:39:02.225 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:39:02.225 [ERROR] [org.gradle.BuildExceptionReporter] 
14:39:02.225 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:39:02.225 [ERROR] [org.gradle.BuildExceptionReporter] Could not resolve all dependencies for configuration ':acceptance-tests:testCompile'.
14:39:02.226 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT.
14:39:02.226 [ERROR] [org.gradle.BuildExceptionReporter]   Required by:
14:39:02.226 [ERROR] [org.gradle.BuildExceptionReporter]       io.spring.cloud.samples.brewery:acceptance-tests:1.0.0 > org.springframework.cloud:spring-cloud-starter-sleuth:1.0.0.BUILD-SNAPSHOT
14:39:02.226 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT.
14:39:02.227 [ERROR] [org.gradle.BuildExceptionReporter]       > Could not parse POM file:/home/centos/.m2/repository/org/springframework/cloud/spring-cloud-sleuth-core/1.0.0.BUILD-SNAPSHOT/spring-cloud-sleuth-core-1.0.0.BUILD-SNAPSHOT.pom
14:39:02.241 [ERROR] [org.gradle.BuildExceptionReporter]          > Unable to resolve version for dependency 'org.assertj:assertj-core:jar'
14:39:02.241 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not resolve org.springframework.cloud:spring-cloud-sleuth-core:1.0.0.BUILD-SNAPSHOT.
14:39:02.241 [ERROR] [org.gradle.BuildExceptionReporter]       > Could not parse POM http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-sleuth-core/1.0.0.BUILD-SNAPSHOT/spring-cloud-sleuth-core-1.0.0.BUILD-20160128.190707-311.pom
14:39:02.241 [ERROR] [org.gradle.BuildExceptionReporter]          > Unable to resolve version for dependency 'org.assertj:assertj-core:jar'
14:39:02.242 [ERROR] [org.gradle.BuildExceptionReporter] 
14:39:02.242 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
14:39:02.242 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
14:39:02.243 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:39:02.243 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED

**Comment by marcingrzejszczak** [comment]
try removing the `~/.gradle` folder and try again.

**Comment by rm2013** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':brewing:compile'.
> Could not resolve org.springframework.cloud:spring-cloud-starter-zookeeper-discovery:1.0.0.BUILD-SNAPSHOT.
  Required by:
      io.spring.cloud.samples.brewery:brewing:1.0.0
   > Could not resolve org.springframework.cloud:spring-cloud-starter-zookeeper-discovery:1.0.0.BUILD-SNAPSHOT.
      > Could not parse POM http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-starter-zookeeper-discovery/1.0.0.BUILD-SNAPSHOT/spring-cloud-starter-zookeeper-discovery-1.0.0.BUILD-20160128.122235-75.pom
         > Unable to resolve version for dependency 'org.springframework.cloud:spring-cloud-starter-archaius:jar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by marcingrzejszczak** [comment]
hmm that's strange. And try to move your `~/.m2` to `~/.m2back` and try again ?

**Comment by rm2013** [comment]
BUILD SUCCESSFUL

Thanks
